apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berget-website
  namespace: berget-web
  annotations:
    external-dns.alpha.kubernetes.io/hostname: feat-pr-preview.stage.berget.ai
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Preview-Environment "PR-40" always;
spec:
  tls:
    - hosts:
        - feat-pr-preview.stage.berget.ai
      secretName: berget-preview-feat-pr-preview-tls
  rules:
    - host: feat-pr-preview.stage.berget.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berget-website
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: berget-custom-headers-configmap
  namespace: berget-web
data:
  Content-Security-Policy: "default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; connect-src 'self' https://api.stage.berget.ai; base-uri 'self'; form-action 'self'; frame-src 'none'; frame-ancestors 'none'; object-src 'none'; worker-src 'self'; manifest-src 'self'; upgrade-insecure-requests;"
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-Xss-Protection: '0'
  Strict-Transport-Security: 'max-age=31536000; includeSubDomains; preload'
  Cross-Origin-Resource-Policy: same-site
  Referrer-Policy: strict-origin
