apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preview-feat-pr-preview

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - ingress-patch.yaml
  - deployment-patch.yaml

images:
  - name: ghcr.io/berget-ai/landing-page
    newTag: 'pr-40'

labels:
  - pairs:
      environment: preview
      pr-number: '40'
