apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berget-website
  namespace: berget-web
spec:
  tls:
    - hosts:
        - berget.ai
        - www.berget.ai
        - berget.cloud
        - www.berget.cloud
      secretName: berget-ai-tls
  rules:
    - host: berget.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berget-website
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: berget-custom-headers-configmap
  namespace: berget-web
data:
  Content-Security-Policy: "default-src 'self'; script-src 'self' https://*.berget.ai; style-src 'self' https://*.berget.ai; font-src 'self' https://*.berget.ai; img-src 'self' https://*.berget.ai data:; connect-src 'self' https://*.berget.ai https://api.berget.ai; base-uri 'self'; form-action 'self'; frame-src 'none'; frame-ancestors 'none'; object-src 'none'; worker-src 'self'; manifest-src 'self'; upgrade-insecure-requests;"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berget-redirects
  namespace: berget-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://berget.ai/'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.berget.ai
        - berget.cloud
        - www.berget.cloud
      secretName: berget-redirects-tls
  rules:
    - host: www.berget.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berget-website
                port:
                  number: 80
    - host: berget.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berget-website
                port:
                  number: 80
    - host: www.berget.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berget-website
                port:
                  number: 80
