apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: berget-web

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yaml

commonLabels:
  environment: production
