apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: berget-web
resources:
  - ../../base
  - ingress-redirects.yaml
patchesStrategicMerge:
  - ingress-patch.yaml
images:
  - name: ghcr.io/berget-ai/landing-page
    newTag: '1.3.103' # {"$imagepolicy": "flux-system:landingpage:tag"}
labels:
  - pairs:
      environment: production
