apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: berget-web

resources:
  - ../../base
  - ingress-redirects.yaml

patches:
  - path: ingress-patch.yaml

labels:
  - pairs:
      environment: production
