name: Cleanup Preview Environment

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Generate preview slug
        id: slug
        uses: rlespinasse/slugify-value@v1.4.0
        with:
          key: SLUG
          value: ${{ github.head_ref }}
          slug-maxlength: 20

      - name: Remove preview overlay
        run: |
          SLUG="${{ steps.slug.outputs.SLUG }}"
          
          if [ -d "k8s/overlays/preview-$SLUG" ]; then
            echo "Removing preview overlay: preview-$SLUG"
            rm -rf "k8s/overlays/preview-$SLUG"
            git add -A
            
            if ! git diff --staged --quiet; then
              git commit -m "cleanup: remove preview overlay for PR #${{ github.event.number }} ($SLUG)"
              
              # Retry push med exponential backoff
              for i in {1..3}; do
                if git push origin HEAD:main; then
                  echo "Successfully removed preview overlay"
                  break
                else
                  echo "Push failed, retrying in $((2**i)) seconds..."
                  sleep $((2**i))
                  git pull --rebase origin main
                fi
              done
            else
              echo "No changes to commit"
            fi
          else
            echo "Preview overlay preview-$SLUG does not exist"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const slug = '${{ steps.slug.outputs.SLUG }}';
            
            const comment = `## 🧹 Preview Environment Cleaned Up
            
            Preview-miljön för denna PR har rensats bort:
            - Overlay \`k8s/overlays/preview-${slug}/\` har tagits bort
            - Kubernetes-resurser kommer att rensas automatiskt av FluxCD
            
            Tack för ditt bidrag! 🎉`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
